-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 15:43:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-flosNexus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-flosNexus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-flosNexus` DEFAULT CHARACTER SET utf8 ;
USE `db-flosNexus` ;

-- -----------------------------------------------------
-- Table `db-flosNexus`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-flosNexus`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_usuarios` VARCHAR(255) NOT NULL,
  `nome_completo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-flosNexus`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-flosNexus`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(255) NOT NULL,
  `icone_categoria` VARCHAR(255) NULL,
  `descricao_categoria` VARCHAR(750) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-flosNexus`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-flosNexus`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(255) NOT NULL,
  `descricao_produto` VARCHAR(1500) NOT NULL,
  `preco` DECIMAL(50,2) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NULL,
  `quantidade_estoque` INT NULL,
  `categoria_id` BIGINT NULL,
  `usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produto_tb_categoria_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db-flosNexus`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db-flosNexus`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
